name: flutter_client
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.14.0

flutter:
  uses-material-design: true
